export const baseUrl:string="http://localhost:8181/rest/"
export const loginUrl:string=baseUrl+"users/login"
export const placesUrl:string=baseUrl+"places/"
export const clientsUrl:string=baseUrl+"clients/"
export const commandesUrl:string=baseUrl+"orders/"
export const deliveriesUrl:string=baseUrl+"deliveries/"
export const categoriesUrl:string=baseUrl+"categories/"
export const submenusUrl:string=baseUrl+"submenus/"
export const menusUrl:string=baseUrl+"menus/"
export const typesUrl:string=baseUrl+"types/"
export const applicationDeliveryUrl:string=baseUrl+"applicationsDelivery/"
export const applicationPlaceUrl:string=baseUrl+"applicationsPlace/"

